Sprint 2/step 2
arbuznik/react-burger pull request #4
Opened 2023-02-13 14:21 UTC by arbuznik

2023-02-13 16:36 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали очень хорошую работу по добавлению DnD и Redux-а в ваш проект, корректно применили `@reduxjs/toolkit`, реализовали нажатие на переключатель в навигации по ингредиентам, код получился лаконичным, так держать 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Счётчик на карточке ингредиента следует скрывать, если он не был добавлен в конструктор, вместо нуля (см. https://disk.yandex.ru/i/F6WeWITYWLgSmg);
- Для методов, вызывающих API следует предусмотреть экшен `request` или `loading`, который будет вызван перед получением/отправкой данных (полезно для показа лоадера/блокировки UI временно);
- В массиве ингредиентов, который отправляет на сервер, идентификаторы булки следует расположить в начале и в конце, как они располагаются в конструкторе;
- В качестве пустого значения не следует использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам;
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента следует приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-02-13 16:36 UTC, randomroot commented on src/services/slices/order.js
> +    order: {},
🔴 **Нужно исправить:**

В качестве пустого значения не следует использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам (особенно вложенным) и обеспечить легкую проверку на наличие данных в элементе: по законам преобразования в JS соблюдается равенства `null == false`, но `{} == true` и `{ data: data } == true`.

2023-02-13 16:36 UTC, randomroot commented on src/services/slices/ingredient.js
> +    ingredient: {},
🔴 **Нужно исправить:**

В качестве пустого значения не следует использовать пустой объект.

2023-02-13 16:36 UTC, randomroot commented on src/services/slices/ingredients-constructor.js
> +}
🟡 **Можно улучшить:**

Имеет смысл вынести булку в отдельный ключ в рамках стейта, чтобы удобно её контролировать, не осуществляя поиск по массиву с ингредиентами

2023-02-13 16:36 UTC, randomroot commented on src/services/slices/ingredients-constructor.js
> +    return state.ingredientsConstructor.ingredients.filter(ingredient => ingredient._id === id).length
🟡 **Можно улучшить:**

Подсчёт кол-ва элементов, добавленных в конструктор осуществляется правильно, однако не совсем оптимально, по причине того, что для каждого ингредиента осуществляется полный проход по всему массиву ингредиентов в поиске совпадающих. Если считать, что длина массива = N, то сложность данного алгоритма в целом для всех элементов = O(N*N), что при большом количестве элементов может ухудшать производительность вашего проекта.

Для оптимизации данного процесса имеет смысл рассмотреть альтернативный путь подсчёта, например проводить его в сторе, храня значения счётчиков там в отдельном объекте и изменяя его показатели при каждом добавлении/удалении элемента. Таким образом, вычислительная сложность уменьшается до O(1), т.к. сложность процесса вычисления не будет зависеть от размера массива.

О вычислительной сложности можно прочитать например здесь: https://tproger.ru/articles/computational-complexity-explained/

2023-02-13 16:36 UTC, randomroot commented on src/components/burger-ingredients/BurgerIngredients.jsx
> +            <div onScroll={handleIngredientsScroll} className={styles.categoriesContainer}>
🟡 **Можно улучшить:**

Обратите внимание, что `onScroll` в исходном виде может быть весьма неэффективным, т.к. будет срабатывать при малейшем движении много раз. Имеет смысл рассмотреть возможность применения `throttle`-функции (см. https://learn.javascript.ru/task/throttle) или упростить задачу, используя специальную библиотеку `react-intersection-observer`

2023-02-13 16:36 UTC, randomroot commented on src/components/burger-constructor/BurgerConstructor.jsx
> +            ingredients: [...fillings.map(filling => filling._id), bun._id]
🔴 **Нужно исправить:**

1) В массиве ингредиентов, который отправляет на сервер, идентификаторы булки следует расположить в **начале** и в **конце**, как они располагаются в конструкторе;
2) Функция `map` возвращает новый массив, поэтому не следует делать его ручную копию с помощью `spread` оператора

2023-02-13 16:36 UTC, randomroot commented on src/components/burger-constructor/BurgerConstructor.jsx
> +            constructorIngredientId: Math.random().toString().slice(8)
🟡 **Можно улучшить:**

Данная функция не гарантирует выдачу уникальных значений (в теории возможны коллизии), целесообразно применить специальную библиотеку `uuid`

2023-02-13 16:36 UTC, randomroot commented on src/components/burger-constructor-filling/BurgerConstructorFilling.jsx
> +        <div ref={dropRef} style={{opacity}} className={styles.fillingContainer}>
🟡 **Можно улучшить:**

Имеет смысл разрешить пользователю перенос элементов в конструкторе в том числе и по самой карточке, а не только по иконке, чтобы улучшить пользовательский опыт

2023-02-13 16:36 UTC, randomroot commented on src/components/burger-constructor/BurgerConstructor.jsx
>      const handleClose = () => {
🟡 **Можно улучшить:**

При закрытии модального окна имеет смысл сбрасывать состояние стора конструктора, чтобы пользователь мог начать создание нового заказа

2023-02-13 19:41 UTC, arbuznik commented on src/components/burger-constructor/BurgerConstructor.jsx
> +            ingredients: [...fillings.map(filling => filling._id), bun._id]
2. Я конкатенириую массив айдишников начинок, полученных с помощью map с двумя значения булок. Без спред оператора получится двухуровненвый массив.

2023-02-13 19:56 UTC, randomroot commented on src/components/burger-constructor/BurgerConstructor.jsx
> +            ingredients: [...fillings.map(filling => filling._id), bun._id]
Да, вы правы, приношу свои извинения за некорректный комментарий 🐈

2023-02-13 23:40 UTC, arbuznik commented on src/components/burger-constructor/BurgerConstructor.jsx
> +            ingredients: [...fillings.map(filling => filling._id), bun._id]
Зато все остальные комментарии четко и по делу, большое спасибо!

2023-02-14 13:39 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-02-14 13:46 UTC, merged