Sprint 3/step 1
arbuznik/react-burger pull request #5
Opened 2023-02-20 20:46 UTC by arbuznik

2023-02-20 21:11 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа!
Что понравилось:
- Есть механизм обновления токена
- Пока идёт запрос показывается лоадер
- Правильно настроен роутинг и редиректы для разных сценариев.

Что необходимо исправить:
- Восстановление пароля не работает так как в запросе не передается имейл.
<img width="1440" alt="Снимок экрана 2023-02-21 в 00 04 21" src="https://user-images.githubusercontent.com/60173362/220198183-25b7350b-f663-466a-a743-0bf672498b37.png">

- Кнопка "Сохранить" должна быть задизейблена или скрыта до тех пор пока юзер не внесет изменения в форму.
- Данные форм должны отправляться по событию `onSubmit`

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-20 21:11 UTC, andryxxa93 commented on src/pages/register/RegisterPage.jsx
> +  useEffect(() => {
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-02-20 21:16 UTC, arbuznik commented on src/pages/register/RegisterPage.jsx
> +  useEffect(() => {
У меня стоит флаг onlyUnAuth в ProtectedRoute

2023-02-21 12:36 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-02-21 13:23 UTC, merged